### ISSUE TITLE
This plugin supports for all beacon devices

### ISSUE THREAD

**Issue by sathyapriya31** [frostney/react-native-ibeacon#18]
I am using Light blue bean http://legacy.punchthrough.com/bean/ ble so this plugin support for this device

**Comment by frostney** [comment]
Does Light Blue Bean support the iBeacon specification? The promo video suggests it does.

**Comment by frostney** [comment]
I have updated the readme to indicate that support for all iBeacon-compatible devices is given. If you are run into any specific problems, feel free to open a new issue.
