### ISSUE TITLE
RN update 0.26 breaks `Beacons.getAuthorizationStatus`

### ISSUE THREAD

**Issue by andrekovac** [frostney/react-native-ibeacon#30]
After updating to react native version 0.26, the calling `Beacons.getAuthorizationStatus` returns `'notDetermined'`.

It seems like the new react native update includes some breaking change for this module.
### Version

0.6.0
### Steps to reproduce
1.  Update react native to version 0.26
2.  Call `Beacons.requestWhenInUseAuthorization();`
3.  
### Expected behavior

Authorization granted
### Actual behavior

Authorization is not granted and beacon ranging does not begin.

**Comment by frostney** [comment]
Thank you for reporting the issue. I'll get to it as soon as I can, but it might take me a few days. Feel free to leave suggestions if you find something about why this issue happens.

**Comment by andrekovac** [comment]
False alarm! I accidentally removed `<key>NSLocationWhenInUseUsageDescription</key>` in the `info.plist` file in another commit which caused the issue. 
However, thanks for replying that fast @frostney! I closed this issue now. Sorry for the confusion. At least I can hereby confirm compatibility with RN 0.26.

btw, thanks so much for this great module!
