### ISSUE TITLE
Is it possible to range for any uuid ?

### ISSUE THREAD

**Issue by wcastand** [frostney/react-native-ibeacon#31]
### Version

0.6.0
### Expected behavior

Hi, 
In my project, i need to range a list of beacons but i can't change their uuid. Is it possible to Range for beacons without providing an uuid et get all the beacons in range ?
### Actual behavior

Right now, we have to specified an UUID, so every beacon should have the same UUID which link us to the estimote cloud and their IOS app to update the beacons settings.

**Comment by frostney** [comment]
You have to supply a UUID, which I believe is a restriction by the underlying iOS SDK.
What you can do is give all your beacons you want to monitor the same UUID and give them different major and minor values, depending on how granular you want your region to be monitored. (Only the combination of UUID + Major + Minor is unique.)
If you replace a beacon, you don't need to re-deploy your app, you can change the beacon's UUID to match. For Estimote specifically take a look at this page: https://community.estimote.com/hc/en-us/articles/200868188-How-to-modify-UUID-Major-and-Minor-values-
