### ISSUE TITLE
RCTBridge.h file not found

### ISSUE THREAD

**Issue by mshanak** [frostney/react-native-ibeacon#44]
### Version
0.6.0
 after linking the xcode project 

xcode give me this error 
` "...../ios/RNBeacon.m:11:9: 'RCTBridge.h' file not found" 

..../ios/RNBeacon.m:11:9: 'RCTBridge.h' file not found
`

**Comment by frostney** [comment]
A fix for this has been proposed in #43, closing this as this is a duplicate of #42.
