### ISSUE TITLE
Bridge problem Native React

### ISSUE THREAD

**Issue by stijnvanhulle** [frostney/react-native-ibeacon#45]
### Version
0.6.0

### Steps to reproduce
1. install native react
2. install react-native-ibeacon
3. compile and get a error about the bridge

Fix:
Remove this line #import "RCTBridge.h" in RNBeacon.m solved the problem

**Comment by laibulle** [comment]
Hello, 

you should use React Native 0.39.x because 0.40 introduce a compatibility break.

**Comment by Dri4n** [comment]
i'm have a same problema, but my react-native versión is 0.42.3 D:, any ideas for this issue?

**Comment by stijnvanhulle** [comment]
Remove this line #import "RCTBridge.h" in RNBeacon.m solved the problem
This works on react native 0.40 and higher
