### ISSUE TITLE
5 minutes to start monitoring!

### ISSUE THREAD

**Issue by johnlev** [frostney/react-native-ibeacon#48]
### Version
0.6.0

### Steps to reproduce
1.  I define my region
`var region = {
    identifier: 'DALI lab',
    uuid: 'F2363048-F649-4537-AB7E-4DADB9966544'
};`
2. I request authorization (which I have confirmed I have) and start monitoring
 `Beacons.requestAlwaysAuthorization();
Beacons.startMonitoringForRegion(region);`
3. I start listening

         var sub1 = DeviceEventEmitter.addListener('regionDidEnter', 
              (enterRegion) => {
                console.log("Enter region: " + JSON.stringify(region));
                this.setState({
                  inDALI: true,
                })

                Beacons.startRangingBeaconsInRegion(region);
            })
4. They are called almost 5 minutes after I defined the listeners with my beacons being turned on and off all the time during

### Expected behavior
They should be called soon after registering a listener if a bacon range is entered or exited

### Actual behavior
It takes a long time

**Comment by MacKentoch** [comment]
Seems like no more maintained? (*Hope I'm wrong*)
